<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $challenges = ['Udělej dnes 30 kliků',
            'Nech v nákupním automatu peníze pro někoho dalšího',
            'Napiš někomu dopis',
            'Pochval dnes alespoň 5 lidí',
            'Projdi se venku bos',
            'Vstaň od počítače a jdi někam kde svítí měsíc',
            'Pozvi někoho k sobě domů',
            'Dej bezdomovci jídlo, či peníze', 'Dnes jez pouze zdravě',
            'Dej se dnes do řeči s člověkem, se kterým běžně nemluvíš',
            'Pokud někde uvidíš odpadek, vyhoď ho!',
            'Pozvi někoho na kávu a dort',
            'Dnes místo jízdy MHD choď jen pěšky',
            'Jdi si zaběhat',
            'Dej dárek někomu, kdo od tebe ještě nikdy dárek nedostal',
            'Usměj se dnes alespoň na tři lidi',
            'Připrav se na zítra do školy/práce více než obvykle',
            'Kup si křupky a podívej se večer na nějaký film v posteli',
            'Dnes buď offline - nezapínej mobil, nebo ho nech doma v šuplíku a zkus to bez něj',
            'Udělej 30 dřepů',
            'Kup někomu květinu',
            'Poruš libovolný zákaz',
            'Dnes na každou výzvu říkej „ano“ nesmíš odmítnout vůbec nic',
            'Napiš báseň',
            'Něco namaluj nebo nakresli',
            'Vypni si telefon',
            'Až půjdeš nebo pojedeš z práce nebo ze školy, zvol úplně jinou trasu',
            'Přečti alespoň jednu kapitolu libovolné knihy',
            'Něco upeč nebo uvař',
            'Věnuj část dne úklidu',
            'Vymaluj pokoj, zmeň uspořádíní nábytku, pověs nový obraz, kup si něco do bytu nebo jinak zkrášli byt',
            'Seznam se s někým novým',
            'Dnes někoho obejmi!',
            'Napiš někomu, komu normálně nepíšeš',
            'Vyfoť dnes něco, co jsi zažil/a',
            'Pomož někomu na zpovednice.cz',
            'Najdi kešku v tvém okolí',
            'Jdi na procházku',
            'Naplánuj výlet s kamarády',
            'Jdi do knihovny a zkus si vybrat něco, co tě zaujme a půjč si to',
            'Nabídni někomu pomoc',
            'I když to běžně neděláš, zkus meditaci',
            'Dnes se nauč nějakou novou dovednost (nový recept, melodii na kytaru, tanec, píseň, cvik, ...)',
            'Zkus postcrossing a ještě dnes odešli pohled do světa',
            'Pozvi někoho na své oblíbené jídlo!',
            'Sedni si například v dopravním prostředku nebo v jídelně k někomu novému',
            'Napiš si na papír 101 svých přání a dej si je někam na oči',
            'Dnes někoho obejmi!',
            'Obdaruj někoho',
            'Napiš list do deníku o dnešním dni (i když si deník nevedeš)',
            'Pozvi někoho k sobě',
            'Řekni někomu, že si ho vážíš',
            'Udělej nějaký dobrý skutek',
            'Dneska pij jen čistou vodu',
            'Místo nápoje, co piješ běžně si objednej něco jiného',
            'Nejzajímavější místo v okolí, které bys doporučil zahraničním turistům navštiv sám nebo s přáteli',
            'Napiš první Elišce, co máš v kontaktech nebo na Messengeru',
            'Přispěj bezdomovci na živobytí',
            'Nech v automatu drobné',
            'Udělej večer táborák, nebo romantiku při svíčkách',
            'Zapiš se do nějakého kurzu',
            'Zamysli se nad tím, co si přeješ a jedno přání si hned splň',
            'Napiš něco motivačního, dej do obálky a nech na veřejném místě',
            'Věnuj se svým koníčkům',
            'Špehuj a šmíruj lidi a něco zajímavého se dozvíš',
            'Vyprávěj někomu, co se ti někdy zdálo v noci',
            'Dnes nevyřkni ani jednu lež',
            'Vyfoť se s lednicí na Instagram',
            'Napiš zprávu tomu, kdo je jako dvacátý v pořadí na Messengeru',
            'Pozvi své kamarády na neexistující oslavu',
            'Lehni si do postele a pusť si film',
            'Přesně ve 14:25 jdi na náměstí a udělej foto #vyzvadne',
            'Vyzkoušej nový drink nebo jídlo, které jsi nikdy neměl',
            'Ukaž světu na Instagramu, co zrovna čteš',
            'Vydej se na výlet někam, kde to neznáš',
            'Jdi do obchodu a pozvi jiného zákazníka na nanuka',
            'Udělej dadaistickou báseň rozstříháním tvých starých školních zápisků',
            'Vem si každou ponožku jiné barvy',
            'Nos rozpuštěné vlasy',
            'Kup si jízdenku na osmou vlakovou zastávku od té tvé a udělej si tam výlet',
            'V noci před spaním vyjdi ven a pozoruj oblohu',
            'Napiš dopis pro kohokoliv a nech ho ležet ve veřejném prostoru',
            'Dnes je žlutý den - obleč si trochu žluté',
            'Pusť si hudbu, kterou ti doporučí kamarád, kterého znáš ze střední',
            'Vyskládej všechny tvé knihy na zem a vyfoť je na Instagram',
            'Vystrč reproduktor z okna a pusť naplno tvou oblíbenou skladbu',
            'Nerozsvěcuj večer světla, zkus svíčky',
            'Uvař',
            'Namaluj křídou na chodník skákacího panáka',
            'Popřej na ulici dobrý den několika cizím lidem',
            'Pusť si večer film',
            'Slep dvě stránky učebnice k sobě',
            'Vystup z MHD o zastávku dříve. To dojdeš',
            'Pochval styl oblékání dvěma lidem',
            'Napiš prvnímu Martinovi, co máš v kontaktech nebo na Messengeru',
            'Napiš někomu, komu normálně nepíšeš',
            'Vyfoť dnes něco, co jsi zažil/a',
            'Usmívej se na všechny',
            'Hoď do random schránky vzkaz',
            'Změň image, tak aby ses nepoznal',
            'Vyhrožuj někomu rozbitím huby',
            'Pomodli se',
            'Pověs si jméno toho, koho máš rád na nástěnku',
            'Pošli odkaz na web Výzva dne dalším lidem',
            'Plať penězi ze hry Dostihy a sázky',
            'Běž do antikvariátu a kup si starou mapu tvé oblasti',
            'Sdílej trasu, kam chodíš rád na procházku',
            'Nauč se něco nového. Cokoliv',
            'Nakresli na nějaké místo sprostý symbol',
            'Kup si čokoládu',
            'Dělej dnes něco pro rozvoj svého talentu',
            'Přečti si kousek Bible',
            'Sežeň pohlednici svého bydliště a odešli na random adresu z mapy',
            'Obleč si triko naruby',
            'Najdi náhodnou lokaci v okolí pomocí této stránky a vyfoť se tam www.geomidpoint.com/random/',
            'Dnes je červený den - obleč se červeně',
            'Obdaruj někoho',
            'Nech v automatu drobné',
            'Zaběhej si',
            'Seznam se s někým novým',
            'Usměj se na ulici na pět lidí',
            'Oslov dnes několik lidí špatným jménem',
            'Natoč video z cesty do práce nebo školy',
            'Oceň styl oblékání neznámému člověku',
            'Přesně ve 14:25 udělej foto v posteli #vyzvadne',
            'Usmívej se na lidi',
            'Nedívej se do mobilu, až budeš na něco čekat. Raději mluv s lidma',
            'Sdílej pokud možno celý seznam skladeb, které jsi dnes poslouchal',
            'Napiš Aničce, ať ti doporučí film na večer',
            'Někoho obejmi',
            'Zeptej si Marka, kde bere odvahu',
            'Nesedej si nikde sám. Přisedni si v MHD k někomu a dej se do řeči',
            'Projdi se venku bos',
            'Vypni si telefon',
            'Napiš povídku z aktuálních pocitů',
            'Naschvál kašlej a během toho pronášej nenápadně sprostá slova',
            'Doporuč kolemjdoucímu nového pediatra',
            'Zeptej se dnes někoho na cestu do pekla',
            'Dneska hodně dupej',
            'Napiš nám do directu na Instagramu nápad na další výzvy!',
            'Přidej se do zájmové skupiny na Facebooku, která tě absolutně nezajímá a začni tam trollit',
            'Poslechni cokoliv, co ti dnes kdo řekne',
            'Ber kamínky z cesty nebo šišky v lese a házej s nimi agresivně o zem',
            'Až si budeš sedat, zaber co nejvíce místa',
            'Zavolej na mobil všem, kteří jsou ve škole a mají zrovna vyučování',
            'Dnes se dívej místo videí pro dospělé na českou pohádku',
            'Napiš SMS Karolíně, že se bohužel zpozdíš',
            'Najdi ve svých věcech něco archivního z dětství a vyfoť',
            'Kartičku do knihovny ponoř do čaje, zahrabej do hlíny, pomlať kladivem... a vše dokumentuj',
            'Omylem zakopni a spadni někde na veřejnosti',
            'Vyzkoušej skok daleký při vystupování z autobusu, či vlaku',
            'Dnes je den objímají, objímej!',
            'Horlivě tleskej člověku, který přejde přes přechod',
            'Podrž někomu dveře',
            'Zavolej Zdendovi, že ty prachy chceš do středy, jinak bude problém',
            'Odposlouchávej a šmíruj lidi',
            'Mluv dvakrát hlasitěji než mluvíš normálně',
            'Vyfoť, na čem právě pracuješ, ať to svět ví',
            'Říkej „ano“ na každou výzvu',
            'Zacvič si',
            'Mluv s každým koho potkáš',
            'Přihlas nepříjemnou šéfovou k odběru reklamního sdělení',
            'Rozpusť si vlasy',
            'Zatanči si',
            'Jsi se večer projít při měsíčku',
            'Nauč se něco nového',
            'Popřej na ulici dobrý den několika cizím lidem.',
            'Dostaň se na místo s výhledem a přemýšlej o světě',
            'Udělej deset kliků na chodníku před poštou',
            'Jsi do práce nebo školy bez bot',
            'Chrochtej na lidi ve vestibulu nádráží',
            'Zakecej se s důchodcem sedícím na lavičce',
            'Přesvědč někoho o tom, že záchody jsou mimo provoz.',
            'Vynes na povrch tu nejdivnější a nejškaredější fotku svýho kámoše',
            'Dostaň ban na Facebook stránce SPD',
            'Poruš libovolný zákaz',
            'Jakmile uslyšíš něco vtipného, směj se jak nejvíc dokážeš',
            'Říkej trapné a ubohé vtipy',
            'Obejmi svou nejlepší kamarádku a řekni jí, že si jí vážíš',
            'Pozvi někoho na drink nebo ho vem na pivo',
            'Zpívej si k hudbě, co ti jde do sluchátek',
            'Kup coffee to go někomu sympatickému, koho potkáš',
            'Nech jednu jízdenku v automatu pro někoho dalšího. Natoč nálezce #vyzvadne',
            'Všem vykej',
            'Všem tykej',
            'Komentuj nahlas všechno, co se kolem tebe děje',
            'Vymysli si svou vlastní výzvu a pošli nám ji',
            'Přidej dvě stejné fotky na Instagram',
            'Přidej si na Facebooku toho, komu jsi žádost nepotvrdil už přes dva roky',
            'Napiš Honzovi, že by si tu modrou košili mohl občas vyprat',
            'Těsně před spaním zavolej svým kámošům, jestli nechtějí jít do klubu',
            'Vyfoť si selfie jak ležíš na chodníku poblíž centra',
            'Dej se do řeči s člověkem, který na sobě bude mít cokoliv červeného',
            'Usměj se na každou sympatickou osobu',
            'Jdi pěšky domů',
            'Při každé činnosti se snaž udělat co nejvější hluk',
            'Špehuj a šmíruj lidi a něco zajímavého se dozvíš',
            'Poděl se s někým o své jídlo',
            'Napiš báseň a nech ji ve veřejném prostoru',
            'Dnes na vše říkej „ano“',
            'Napiš někomu, komu jsi už dlouho nenapsal',
            'Usměj se na každého, kdo je nižší než ty',
            'Jeď dnes někam vlakem',
            'Zeptej se někoho na cestu a pak odejdi opačným směrem',
            'Pochval někomu nějakou část oblečení',
            'Říkej novým lidem jméno tvého kamaráda, místo svého',
            'Seber ze země něco, co patří do koše a do koše to dej',
            'Zapni si v mobilu režim letadlo',
            'Vyjdi schody pozadu',
            'Zdrav opravdu velmi hlasitě',
            'Sdílej, co máš rád za hudbu',
            'Popřej svému kamarádovi k fiktivním narozeninám',
            'Pusť si Český Rozhlas Junior',
            'Sedni si někam na lavičku a jenom tak pozoruj lidi',
            'Alesoň jednou dnes překonej strach',
            'Oslov někoho sympatického',
            'Nauč se milostnou báseň',
            'Vyfoť a sdílej aktuální stranu knihy, kterou čteš',
            'Okomentuj deset příspěvků na Facebooku',
            'Dnes nevyřkni ani jednu lež',
            'Vyfoť se s lednicí na Instagram',
            'Napiš zprávu tomu, kdo je jako dvacátý v pořadí na Messengeru',
            'Pozvi své kamarády na neexistující oslavu',
            'Lehni si do postele a pusť si film',
            'Přesně ve 14:25 jdi na náměstí a udělej foto #vyzvadne',
            'Vyzkoušej nový drink nebo jídlo, které jsi nikdy neměl',
            'Ukaž světu na Instagramu, co zrovna čteš',
            'Vydej se na výlet někam, kde to neznáš',
            'Jdi do obchodu a pozvi jiného zákazníka na nanuka',
            'Udělej dadaistickou báseň rozstříháním tvých starých školních zápisků',
            'Vem si každou ponožku jiné barvy',
            'Nos rozpuštěné vlasy',
            'Kup si jízdenku na osmou vlakovou zastávku od té tvé a udělej si tam výlet',
            'V noci před spaním vyjdi ven a pozoruj oblohu',
            'Napiš dopis pro kohokoliv a nech ho ležet ve veřejném prostoru',
            'Dnes je žlutý den - obleč si trochu žluté',
            'Pusť si hudbu, kterou ti doporučí kamarád, kterého znáš ze střední',
            'Vyskládej všechny tvé knihy na zem a vyfoť je na Instagram',
            'Vystrč reproduktor z okna a pusť naplno tvou oblíbenou skladbu',
            'Nerozsvěcuj večer světla, zkus svíčky',
            'Uvař',
            'Namaluj křídou na chodník skákacího panáka',
            'Popřej na ulici dobrý den několika cizím lidem',
            'Pusť si večer film',
            'Slep dvě stránky učebnice k sobě',
            'Vystup z MHD o zastávku dříve. To dojdeš',
            'Pochval styl oblékání dvoum lidem',
            'Napiš prvnímu Martinovi, co máš v kontaktech nebo na Messengeru',
            'Napiš někomu, komu normálně nepíšeš',
            'Vyfoť dnes něco, co jsi zažil/a',
            'Usmívej se na všechny',
            'Hoď do random schránky vzkaz',
            'Změň image, tak aby ses nepoznal',
            'Vyhrožuj někomu rozbitím huby',
            'Pomodli se',
            'Pověs si jméno toho, koho máš rád na nástěnku',
            'Pošli odkaz na web Výzva dne dalším lidem',
            'Plať penězi ze hry Dostihy a sázky',
            'Běž do antikvariátu a kup si starou mapu tvé oblasti',
            'Sdílej trasu, kam chodíš rád na procházku',
            'Nauč se něco nového. Cokoliv',
            'Nakresli na nějaké místo sprostý symbol',
            'Kup si čokoládu',
            'Dělej dnes něco pro rozvoj svého talentu',
            'Přečti si kousek Bible',
            'Sežeň pohlednici svého bydliště a odešli na random adresu z mapy',
            'Obleč si triko naruby',
            'Najdi náhodnou lokaci v okolí pomocí této stránky a vyfoť se tam www.geomidpoint.com/random/',
            'Dnes je červený den - obleč se červeně',
            'Obdaruj někoho',
            'Nech v automatu drobné',
            'Zaběhej si',
            'Seznam se s někým novým',
            'Usměj se na ulici na pět lidí',
            'Oslov dnes několik lidí špatným jménem',
            'Natoč video z cesty do práce nebo školy',
            'Oceň styl oblékání neznámému člověku',
            'Přesně ve 17:25 udělej foto v posteli #vyzvadne',
            'Usmívej se na lidi',
            'Nedívej se do mobilu, až budeš na něco čekat. Raději mluv s lidma',
            'Sdílej pokud možno celý seznam skladeb, které jsi dnes poslouchal',
            'Napiš Aničce, ať ti doporučí film na večer',
            'Někoho obejmi',
            'Zeptej si Marka, kde bere odvahu',
            'Nesedej si nikde sám. Přisedni si v MHD k někomu a dej se do řeči',
            'Projdi se venku bos',
            'Vypni si telefon',
            'Napiš povídku z aktuálních pocitů',
            'Naschvál kašlej a během toho pronášej nenápadně sprostá slova',
            'Doporuč kolemjdoucímu nového pediatra',
            'Zeptej se dnes někoho na cestu do pekla',
            'Dneska hodně dupej',
            'Napiš nám do directu na Instagramu nápad na další výzvy!',
            'Přidej se do zájmové skupiny na Facebooku, která tě absolutně nezajímá a začni tam trollit',
            'Poslechni cokoliv, co ti dnes kdo řekne',
            'Ber kamínky z cesty nebo šišky v lese a házej s nimi agresivně o zem',
            'Až si budeš sedat, zaber co nejvíce místa',
            'Zavolej na mobil všem, kteří jsou ve škole a mají zrovna vyučování',
            'Dnes se dívej místo videí pro dospělé na českou pohádku',
            'Napiš SMS Karolíně, že se bohužel zpozdíš',
            'Najdi ve svých věcech něco archivního z dětství a vyfoť',
            'Kartičku do knihovny ponoř do čaje, zahrabej do hlíny, pomlať kladivem... a vše dokumentuj',
            'Omylem zakopni a spadni někde na veřejnosti',
            'Vyzkoušej skok daleký při vystupování z autobusu, či vlaku',
            'Dnes je den objímají, objímej!',
            'Horlivě tleskej člověku, který přejde přes přechod',
            'Podrž někomu dveře',
            'Zavolej Zdendovi, že ty prachy chceš do středy, jinak bude problém',
            'Odposlouchávej a šmíruj lidi',
            'Mluv dvakrát hlasitěji než mluvíš normálně',
            'Vyfoť, na čem právě pracuješ, ať to svět ví',
            'Říkej „ano“ na každou výzvu',
            'Zacvič si',
            'Mluv s každým koho potkáš',
            'Přihlas nepříjemnou šéfovou k odběru reklamního sdělení',
            'Rozpusť si vlasy',
            'Zatanči si',
            'Jsi se večer projít při měsíčku',
            'Nauč se něco nového',
            'Popřej na ulici dobrý den několika cizím lidem.',
            'Dostaň se na místo s výhledem a přemýšlej o světě',
            'Udělej deset kliků na chodníku před poštou',
            'Jdi do práce nebo školy bez bot',
            'Chrochtej na lidi ve vestibulu nádráží',
            'Zakecej se s důchodcem sedícím na lavičce',
            'Přesvědč někoho o tom, že záchody jsou mimo provoz.',
            'Vynes na povrch tu nejdivnější a nejškaredější fotku svýho kámoše',
            'Dostaň ban na Facebook stránce SPD',
            'Poruš libovolný zákaz',
            'Jakmile uslyšíš něco vtipného, směj se jak nejvíc dokážeš',
            'Říkej trapné a ubohé vtipy',
            'Obejmi svou nejlepší kamarádku a řekni jí, že si jí vážíš',
            'Rozházej papírky se symbolem pentagramu do svěcené vody v kostele',
            'Zpívej si k hudbě, co ti jde do sluchátek',
            'Kup coffee to go někomu sympatickému, koho potkáš',
            'Nech jednu jízdenku v automatu pro někoho dalšího. Natoč nálezce #vyzvadne',
            'Všem vykej',
            'Všem tykej',
            'Komentuj nahlas všechno, co se kolem tebe děje',
            'Vymysli si svou vlastní výzvu a pošli nám ji',
            'Přidej dvě stejné fotky na Instagram',
            'Přidej si na Facebooku toho, komu jsi žádost nepotvrdil už přes dva roky',
            'Napiš Honzovi, že by si tu modrou košili mohl občas vyprat',
            'Těsně před spaním zavolej svým kámošům, jestli nechtějí jít do klubu',
            'Vyfoť si selfie jak ležíš na chodníku poblíž centra',
            'Dej se do řeči s člověkem, který na sobě bude mít cokoliv červeného',
            'Usměj se na každou sympatickou osobu',
            'Jdi pěšky domů',
            'Při každé činnosti se snaž udělat co nejvější hluk',
            'Špehuj a šmíruj lidi a něco zajímavého se dozvíš',
            'Poděl se s někým o své jídlo',
            'Napiš báseň a nech ji ve veřejném prostoru',
            'Dnes na vše říkej „ano“',
            'Napiš někomu, komu jsi už dlouho nenapsal',
            'Usměj se na každého, kdo je nižší než ty',
            'Jeď dnes někam vlakem',
            'Zeptej se někoho na cestu a pak odejdi opačným směrem',
            'Pochval někomu nějakou část oblečení',
            'Říkej novým lidem jméno tvého kamaráda, místo svého',
            'Seber ze země něco, co patří do koše a do koše to dej',
            'Zapni si v mobilu režim letadlo',
            'Vyjdi schody pozadu',
            'Zdrav opravdu velmi hlasitě',
            'Sdílej, co máš rád za hudbu',
            'Popřej svému kamarádovi k fiktivním narozeninám',
            'Pusť si Český Rozhlas Junior',
            'Sedni si někam na lavičku a jenom tak pozoruj lidi',
            'Alesoň jednou dnes překonej strach',
            'Oslov někoho sympatického',
            'Nauč se milostnou báseň',
            'Vyfoť a sdílej aktuální stranu knihy, kterou čteš',
            'Okomentuj deset příspěvků na Facebooku'];

        for ($i = 1; $i <= 365 ; $i++) {
            DB::table('challenges')->insert([
                'day' => $i,
                'challenge_name' => $challenges[$i],
                'secret_id' => Str::random(10),
            ]);
        }
    }
}
